"""Reproducible report generator.

Reads this project's own generated result files (results/metrics/*.json,
dataset/dcase_part1/splits/build_manifests_summary.json, and, once they
exist, results/predictions/predictions.jsonl and logs/training_log.jsonl)
and writes docs/final_report.md, then converts it to
docs/Audio_Context_Layer_Final_Report.pdf.

No number in the generated report is hand-typed: every data-driven table
below is built from a loaded JSON/JSONL file. Sections that depend on
training or evaluation artifacts describe the pipeline when those files
are absent; re-run this script after `scripts/evaluate.py` to embed
measured model metrics.
"""

from __future__ import annotations

import _path_setup  # noqa: F401

import json
from pathlib import Path

from src.utils.paths import resolve_project_path

ROOT = resolve_project_path(".")
DOCS = ROOT / "docs"


def load_json(rel_path: str) -> dict | None:
    path = ROOT / rel_path
    if not path.exists():
        return None
    return json.loads(path.read_text(encoding="utf-8"))


def load_jsonl(rel_path: str) -> list[dict] | None:
    path = ROOT / rel_path
    if not path.exists():
        return None
    return [json.loads(line) for line in path.open(encoding="utf-8") if line.strip()]


def count_tests_passing() -> tuple[int, int]:
    import subprocess
    import sys

    result = subprocess.run(
        [sys.executable, "-m", "unittest", "discover", "-s", "tests"],
        cwd=str(ROOT), capture_output=True, text=True,
    )
    tail = result.stderr.strip().splitlines()
    ran = 0
    for line in tail:
        if line.startswith("Ran "):
            ran = int(line.split()[1])
    passed = ran if result.returncode == 0 else 0
    return passed, ran


def render_results_table(overall: dict | None, split_report: dict, integrity: dict, manifest_summary: dict, answer_consistency: dict, tests_passed: int, tests_total: int) -> str:
    rows = [
        "| Metric | Value | Source |",
        "|---|---:|---|",
        f"| Train / validation / test records | {split_report['splits']['train']['records']:,} / {split_report['splits']['validation']['records']:,} / {split_report['splits']['test']['records']:,} | `results/metrics/data_split_validation.json` |",
        f"| Cross-split audio overlap (train∩val, train∩test, val∩test) | {split_report['overlaps']['train__validation']['count']} / {split_report['overlaps']['test__train']['count']} / {split_report['overlaps']['test__validation']['count']} | `scripts/validate_splits.py` |",
        f"| Manifest-referenced audio files decodable | {integrity['decodable']:,} / {integrity['total_unique_audio_checked']:,} ({100*integrity['decodable']/integrity['total_unique_audio_checked']:.0f}%) | `results/metrics/audio_integrity.json` |",
        f"| Answer/choice records resolved by normalization | {answer_consistency['resolved_by_trailing_punctuation_normalization']} / {answer_consistency['raw_mismatch_count']} | `src/data/validation.py:answer_choice_consistency` |",
        f"| Automated unit tests passing | {tests_passed} / {tests_total} | `tests/` (`python -m unittest discover -s tests`) |",
    ]
    if overall is not None:
        rows.append(f"| Overall test accuracy | {overall['accuracy']*100:.2f}% | `results/metrics/overall_metrics.json` |")
        rows.append(f"| Correct / Incorrect (test) | {overall['correct_count']} / {overall['incorrect_count']} | `results/metrics/overall_metrics.json` |")
    return "\n".join(rows)


def render_question_type_results(by_type: dict | None) -> str:
    if by_type is None:
        return (
            "The evaluation pipeline (`src/evaluation/metrics.py:accuracy_by_field`) computes this "
            "breakdown from `results/predictions/predictions.jsonl`, keyed on the same `question_type` "
            "values shown in Section 5. Regenerate this report after evaluation to embed the table here."
        )
    lines = ["| Question type | Accuracy | Correct | Incorrect | Total |", "|---|---:|---:|---:|---:|"]
    for qtype, stats in sorted(by_type.items()):
        lines.append(f"| {qtype} | {stats['accuracy']*100:.2f}% | {stats['correct_count']} | {stats['incorrect_count']} | {stats['total_count']} |")
    return "\n".join(lines)


def render_loss_curves(has_log: bool) -> str:
    if not has_log:
        return (
            "`src/training/plots.py:plot_training_curves` reads `logs/training_log.jsonl` and writes "
            "`results/plots/training_loss.png`, `results/plots/validation_loss.png`, and "
            "`results/plots/learning_rate.png`. Those plots are referenced in the regenerated report when the log exists."
        )
    return (
        "Training was run and produced loss logs; see `results/plots/training_loss.png`, "
        "`results/plots/validation_loss.png`, and `results/plots/learning_rate.png`, generated by "
        "`src/training/plots.py:plot_training_curves` from `logs/training_log.jsonl`."
    )


def render_error_analysis(errors: list[dict] | None) -> str:
    if errors is None:
        return (
            "`src/evaluation/error_analysis.py` groups incorrect predictions by `question_type` and preserves the "
            "full context (audio, question, choices, expected answer, model response) for inspection. Analysis "
            "should distinguish observed acoustic evidence from inferred answers per question type, and should not "
            "attribute a failure to \"reasoning\" or \"causal\" difficulty for a question type this dataset does not "
            "actually label as such (Section 2)."
        )
    from collections import Counter

    by_type = Counter(e.get("question_type") or "unknown" for e in errors)
    lines = [f"{len(errors)} incorrect predictions on the test set. By question type:", "", "| Question type | Errors |", "|---|---:|"]
    for qtype, count in sorted(by_type.items()):
        lines.append(f"| {qtype} | {count} |")
    return "\n".join(lines)


def build_markdown() -> str:
    split_report = load_json("results/metrics/data_split_validation.json")
    integrity_full = load_json("results/metrics/audio_integrity.json")
    integrity = integrity_full["summary"] if integrity_full else None
    manifest_summary = load_json("dataset/dcase_part1/splits/build_manifests_summary.json")
    overall = load_json("results/metrics/overall_metrics.json")
    by_type = load_json("results/metrics/question_type_metrics.json")
    training_log = load_jsonl("logs/training_log.jsonl")
    predictions = load_jsonl("results/predictions/predictions.jsonl")
    errors = load_jsonl("results/error_analysis/errors.jsonl")

    if split_report is None or integrity is None or manifest_summary is None:
        raise SystemExit(
            "Missing required result files. Run scripts/validate_splits.py and "
            "scripts/validate_audio_integrity.py before generating the report."
        )

    answer_consistency = split_report["splits"]["test"]["answer_choice_consistency"]
    tests_passed, tests_total = count_tests_passing()

    qtype_dist = split_report["splits"]
    qtype_rows_train = qtype_dist["train"]["question_type_distribution"]
    qtype_rows_test = qtype_dist["test"]["question_type_distribution"]
    dominant_train = max(qtype_rows_train.items(), key=lambda kv: kv[1]["count"])[0]
    dominant_test = max(qtype_rows_test.items(), key=lambda kv: kv[1]["count"])[0]

    template_path = ROOT / "docs" / "_final_report_template.md"
    template = template_path.read_text(encoding="utf-8")

    values = dict(
        train_count=split_report["splits"]["train"]["records"],
        validation_count=split_report["splits"]["validation"]["records"],
        test_count=split_report["splits"]["test"]["records"],
        train_unique_audio=split_report["splits"]["train"]["unique_audio_count"],
        validation_unique_audio=split_report["splits"]["validation"]["unique_audio_count"],
        test_unique_audio=split_report["splits"]["test"]["unique_audio_count"],
        raw_train_metadata=manifest_summary["raw_metadata_counts"]["train"],
        raw_dev_metadata=manifest_summary["raw_metadata_counts"]["dev"],
        original_train_count_plus_val=manifest_summary["original_train_count"] + manifest_summary["original_validation_count"],
        audio_total_minus_decodable=integrity["total_unique_audio_checked"] - integrity["decodable"],
        original_train_count=manifest_summary["original_train_count"],
        original_validation_count=manifest_summary["original_validation_count"],
        contaminated_train=manifest_summary["contaminated_train_audio_count"],
        contaminated_validation=manifest_summary["contaminated_validation_audio_count"],
        cleaned_train=manifest_summary["cleaned_train_count"],
        cleaned_validation=manifest_summary["cleaned_validation_count"],
        total_overlap=manifest_summary["contaminated_train_audio_count"] + manifest_summary["contaminated_validation_audio_count"],
        audio_total=integrity["total_unique_audio_checked"],
        audio_decodable=integrity["decodable"],
        audio_riff=integrity["container_type_counts"].get("riff", 0),
        audio_mp3_frame=integrity["container_type_counts"].get("mp3_frame_sync", 0),
        audio_mp3_id3=integrity["container_type_counts"].get("mp3_id3", 0),
        extension_mismatch_total=integrity["extension_mismatch_total"],
        raw_mismatch_count=answer_consistency["raw_mismatch_count"],
        resolved_by_normalization=answer_consistency["resolved_by_trailing_punctuation_normalization"],
        genuinely_malformed=answer_consistency["genuinely_malformed_count"],
        dominant_train_qtype=dominant_train,
        dominant_test_qtype=dominant_test,
        tests_passed=tests_passed,
        tests_total=tests_total,
    )
    # Thousands separators for anything numeric >= 1000, purely cosmetic.
    values = {k: (f"{v:,}" if isinstance(v, int) and v >= 1000 else v) for k, v in values.items()}
    values.update(
        results_table=render_results_table(overall, split_report, integrity, manifest_summary, answer_consistency, tests_passed, tests_total),
        question_type_results=render_question_type_results(by_type),
        loss_curves_section=render_loss_curves(training_log is not None),
        error_analysis_section=render_error_analysis(errors),
    )
    return template.format(**values)


def convert_to_pdf(markdown_path: Path, pdf_path: Path) -> bool:
    """Render the markdown report to a professionally formatted PDF using
    the project's own reportlab-based renderer (scripts/render_pdf.py) --
    no external binary (pandoc, wkhtmltopdf, a GTK/Pango stack) is required,
    which matters on a Windows CPU-only machine where those are painful or
    impossible to install. Returns True on success; callers should not treat
    a failure here as report generation having failed overall -- the
    markdown is the primary, version-controlled artifact regardless.
    """
    from scripts.render_pdf import render_markdown_to_pdf

    try:
        render_markdown_to_pdf(
            markdown_path=markdown_path,
            pdf_path=pdf_path,
            image_root=markdown_path.parent,
            title="Audio Context Layer",
            subtitle="A LoRA-Adapted Qwen2-Audio-7B-Instruct System for the<br/>DCASE 2025 Audio Question Answering Benchmark",
            meta_lines=[
                "Technical Report",
                "Model: Qwen/Qwen2-Audio-7B-Instruct &nbsp;|&nbsp; Dataset: DCASE 2025 Task 5, Part 1",
                "Adaptation: PEFT LoRA (rank 16, language_model.* scope)",
            ],
        )
        return True
    except Exception as exc:
        print(f"PDF rendering failed: {type(exc).__name__}: {exc}")
        return False


def main() -> None:
    from scripts.generate_report_figures import (
        plot_architecture_diagram,
        plot_dcase_reference_comparison,
        plot_pipeline_diagram,
        plot_question_type_distribution,
    )

    plot_question_type_distribution()
    plot_dcase_reference_comparison()
    plot_architecture_diagram()
    plot_pipeline_diagram()

    markdown = build_markdown()
    out_md = DOCS / "final_report.md"
    out_md.write_text(markdown, encoding="utf-8")
    print(f"wrote {out_md}")

    pdf_path = DOCS / "Audio_Context_Layer_Final_Report.pdf"
    if convert_to_pdf(out_md, pdf_path):
        print(f"wrote {pdf_path}")
    else:
        print(f"No local markdown->PDF converter found; {out_md} is the source of truth for the PDF (see docs/ for the rendered PDF produced separately).")


if __name__ == "__main__":
    main()
